version: '3.8'

services:
  flaccy:
    build: .
    container_name: flaccy
    dns:
      - 8.8.8.8
    env_file:
      - .env
    volumes:
      - ./downloads:/app/downloads
    ports:
      - "5000:5000"
    restart: unless-stopped
